import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/ui/theme-provider"
import { TaxHarvestingProvider } from "@/context/TaxHarvestingContext"
import "./globals.css"

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] })

export const metadata: Metadata = {
  title: "KoinX",
  description: "Generated by create next app",
  authors : [{name : 'Gurubrahmam Velpula'}]
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${inter.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <TaxHarvestingProvider>{children}</TaxHarvestingProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
